apiVersion: v1
kind: PersistentVolume
metadata:
  name: flask-app-db-pv
  namespace: flask-app-extions-stage
  labels:
    app: flask-app-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /data/flask-app-db
    server: 192.168.56.11
