kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flask-app-db-pv-claim
  namespace: flask-app-extions-stage
  labels:
    app: flask-app-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
