kind: Service
apiVersion: v1
metadata:
  name: flask-app-nginx
  namespace: flask-app-extions-stage
spec:
  #type: NodePort
  selector:
    app: flask-app-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    #nodePort: 30001
  selector:
    app: flask-app-nginx
