apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: flask-app-extions-stage
  labels:
    app: flask-app
spec:
  ports:
  - protocol: TCP
    port: 3032
    targetPort: 3031
  selector:
    app: flask-app
