# deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app-extions-stage
  labels:
    app: flask-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask-app
        tier: frontend
    spec:
      containers:
      - image: guomaoqiu/python27baseenv:v2
        # 镜像检查有三个选择:
        # IfNotPresent，如果本地有就不检查，如果没有就拉取；
        # Never，每次都不检查（不管本地是否有）
        # Always，每次都检查
        imagePullPolicy: IfNotPresent
        name: flask-app
        command: ["/usr/bin/supervisord"]
        args: ["-c","/usr/local/code/supervisord.conf"]
        env:
        - name: FLASK-APP-DB-PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3031
          name: flask-app
        volumeMounts:
        - name: flask-app-persistent-storage
          mountPath: /usr/local/code
      volumes:
      - name: flask-app-persistent-storage
        persistentVolumeClaim:
          claimName: flask-app-data-pv-claim
