kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flask-app-data-pv-claim
  namespace: flask-app-extions-stage
  labels:
    app: flask-app-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
